set(FILE_GROUP_assemble "")
set(FILE_GROUP_assemblePreprocess "")
set(FILE_GROUP_compile "../../../../main.c")
set(FILE_GROUP_link "")
set(BUILD_LIBRARY 0)
set(internal_image_name "d:/code/uni/AUV/Sonar2/_build_mplab/Sonar/default/image_default.elf/default.elf")
set(image_name "default.elf")
set(output_dir "d:/code/uni/AUV/Sonar2/out/Sonar")
